import type { CPRSkills } from '@/types/index';

export interface CPRSkillDef {
  key: keyof CPRSkills;
  name: string;
  stat: string;
}

export const CPR_SKILL_DEFS: CPRSkillDef[] = [
  { key: 'accounting',             name: 'Accounting',              stat: 'INT'  },
  { key: 'acting',                 name: 'Acting',                  stat: 'COOL' },
  { key: 'airVehicleTech',         name: 'Air Vehicle Tech',        stat: 'TECH' },
  { key: 'animalHandling',         name: 'Animal Handling',         stat: 'INT'  },
  { key: 'archery',                name: 'Archery',                 stat: 'REF'  },
  { key: 'athletics',              name: 'Athletics',               stat: 'DEX'  },
  { key: 'autofire',               name: 'Autofire',                stat: 'REF'  },
  { key: 'basicTech',              name: 'Basic Tech',              stat: 'TECH' },
  { key: 'brawling',               name: 'Brawling',                stat: 'DEX'  },
  { key: 'bribery',                name: 'Bribery',                 stat: 'COOL' },
  { key: 'bureaucracy',            name: 'Bureaucracy',             stat: 'INT'  },
  { key: 'business',               name: 'Business',                stat: 'INT'  },
  { key: 'composition',            name: 'Composition',             stat: 'INT'  },
  { key: 'concealRevealObject',    name: 'Conceal/Reveal Object',   stat: 'INT'  },
  { key: 'concentration',          name: 'Concentration',           stat: 'WILL' },
  { key: 'contortionist',          name: 'Contortionist',           stat: 'DEX'  },
  { key: 'conversation',           name: 'Conversation',            stat: 'EMP'  },
  { key: 'criminology',            name: 'Criminology',             stat: 'INT'  },
  { key: 'cryptography',           name: 'Cryptography',            stat: 'INT'  },
  { key: 'cybertech',              name: 'Cybertech',               stat: 'TECH' },
  { key: 'dance',                  name: 'Dance',                   stat: 'DEX'  },
  { key: 'deduction',              name: 'Deduction',               stat: 'INT'  },
  { key: 'demolitions',            name: 'Demolitions',             stat: 'TECH' },
  { key: 'driveLandVehicle',       name: 'Drive Land Vehicle',      stat: 'REF'  },
  { key: 'education',              name: 'Education',               stat: 'INT'  },
  { key: 'electronicsSecurityTech',name: 'Electronics/Security Tech',stat: 'TECH'},
  { key: 'endurance',              name: 'Endurance',               stat: 'WILL' },
  { key: 'evasion',                name: 'Evasion',                 stat: 'DEX'  },
  { key: 'firstAid',               name: 'First Aid',               stat: 'TECH' },
  { key: 'forgery',                name: 'Forgery',                 stat: 'TECH' },
  { key: 'gamble',                 name: 'Gamble',                  stat: 'INT'  },
  { key: 'handgun',                name: 'Handgun',                 stat: 'REF'  },
  { key: 'heavyWeapons',           name: 'Heavy Weapons',           stat: 'REF'  },
  { key: 'humanPerception',        name: 'Human Perception',        stat: 'EMP'  },
  { key: 'interrogation',          name: 'Interrogation',           stat: 'COOL' },
  { key: 'landVehicleTech',        name: 'Land Vehicle Tech',       stat: 'TECH' },
  { key: 'language',               name: 'Language',                stat: 'INT'  },
  { key: 'librarySearch',          name: 'Library Search',          stat: 'INT'  },
  { key: 'lipReading',             name: 'Lip Reading',             stat: 'INT'  },
  { key: 'localExpert',            name: 'Local Expert',            stat: 'INT'  },
  { key: 'martialArts',            name: 'Martial Arts',            stat: 'DEX'  },
  { key: 'meleeWeapon',            name: 'Melee Weapon',            stat: 'DEX'  },
  { key: 'paintDrawSculpt',        name: 'Paint/Draw/Sculpt',       stat: 'TECH' },
  { key: 'paramedic',              name: 'Paramedic',               stat: 'TECH' },
  { key: 'perception',             name: 'Perception',              stat: 'INT'  },
  { key: 'personalGrooming',       name: 'Personal Grooming',       stat: 'COOL' },
  { key: 'persuasion',             name: 'Persuasion',              stat: 'COOL' },
  { key: 'photographyFilm',        name: 'Photography/Film',        stat: 'TECH' },
  { key: 'pickLock',               name: 'Pick Lock',               stat: 'TECH' },
  { key: 'pickPocket',             name: 'Pick Pocket',             stat: 'TECH' },
  { key: 'pilotAirVehicle',        name: 'Pilot Air Vehicle',       stat: 'REF'  },
  { key: 'pilotSeaVehicle',        name: 'Pilot Sea Vehicle',       stat: 'REF'  },
  { key: 'playInstrument',         name: 'Play Instrument',         stat: 'TECH' },
  { key: 'resistTortureDrugs',     name: 'Resist Torture/Drugs',    stat: 'WILL' },
  { key: 'riding',                 name: 'Riding',                  stat: 'REF'  },
  { key: 'science',                name: 'Science',                 stat: 'INT'  },
  { key: 'seaVehicleTech',         name: 'Sea Vehicle Tech',        stat: 'TECH' },
  { key: 'shoulderArms',           name: 'Shoulder Arms',           stat: 'REF'  },
  { key: 'stealth',                name: 'Stealth',                 stat: 'DEX'  },
  { key: 'streetwise',             name: 'Streetwise',              stat: 'COOL' },
  { key: 'tactics',                name: 'Tactics',                 stat: 'INT'  },
  { key: 'tracking',               name: 'Tracking',                stat: 'INT'  },
  { key: 'trading',                name: 'Trading',                 stat: 'COOL' },
  { key: 'wardrobeStyle',          name: 'Wardrobe & Style',        stat: 'COOL' },
  { key: 'weaponstech',            name: 'Weaponstech',             stat: 'TECH' },
  { key: 'wildernesssurvival',     name: 'Wilderness Survival',     stat: 'INT'  },
];
